### ISSUE TITLE
您好，我按照您的示例操作了，报数据库错误，能帮我看看吗？

### ISSUE THREAD

**Issue by yangqiang5156** [dxxzst/OfflineMap#1]
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'and Zoom=undefined and X=undefined and Y=undefined' at line 1

**Comment by yangqiang5156** [comment]
我看了数据库里有数据了

**Comment by dxxzst** [comment]
你下载谷歌地图试一下，我以谷歌地图为例写的页面

**Comment by livingbody** [comment]
google地图能下载下来吗？不是打不开胡歌地图吗

**Comment by dxxzst** [comment]
可以下载的
