### ISSUE TITLE
工具下载不了mysql数据文件

### ISSUE THREAD

**Issue by Can-Chen** [dxxzst/OfflineMap#10]

**Comment by Can-Chen** [comment]
我需要把mapBox替换成高德 请问有例子吗

**Comment by dxxzst** [comment]
@Can-Chen 肯定是可以下载的，下载不了估计是数据库配置问题。
想换成高德地图，可切换成高德地图再下载。js中调用高德地图的Type代码

**Comment by hundan1** [comment]
下载器里面的存储方式改成musql,还有改下下载器的配置文件，下好后刷新下mysql
