### ISSUE TITLE
你好，我存到数据库中的高德地图瓦片无法显示，报错error while loading image data

### ISSUE THREAD

**Issue by qianxiamoli** [dxxzst/OfflineMap#11]

**Comment by dxxzst** [comment]
首先要确保数据库中已经存储好了对应的瓦片图。
然后在预览页面还要保证加载的type一致。

**Comment by qianxiamoli** [comment]
我想实现的是从数据库中读取瓦片图blob对象并存储在本地，可是发现存储在本地的png图片都无法打开，是不是只有在leaflet中加载相应瓦片时才能显示出来？

**Comment by dxxzst** [comment]
@qianxiamoli 存储在本地可能需要一些格式转换
