### ISSUE TITLE
瓦片数据不连续

### ISSUE THREAD

**Issue by a17853726916** [dxxzst/OfflineMap#13]
下载到数据库中的数据再读取的时候 显示500错误 
下载到本地文件夹的时候读取过程中，因为不连续的问题有一部分数据读取不到

**Comment by dxxzst** [comment]
@a17853726916 下载时可以选择下载层级的，如果区域比较小可以都下载下来

**Comment by a17853726916** [comment]
您好 我选择的图层是比较小的 但是通过示例进行显示的时候 总是显示有的图片读取不到 请问这是什么原因呢





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dxxzst/OfflineMap"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月17日(星期四) 上午9:10
收件人:&nbsp;"dxxzst/OfflineMap"<OfflineMap@noreply.github.com&gt;;
抄送:&nbsp;"于洋"<1158550322@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dxxzst/OfflineMap] 瓦片数据不连续 (#13)





 
@a17853726916 下载时可以选择下载层级的，如果区域比较小可以都下载下来

**Comment by dxxzst** [comment]
@a17853726916 读取不到的可以通过瓦片url查看一下具体参数，去数据库看看有没有下载下来
