### ISSUE TITLE
数据不全

### ISSUE THREAD

**Issue by comewanglei** [dxxzst/OfflineMap#2]
你好 我用软件下载google数据到mysql数据库 数据总是下载不全 想请教一下怎么回事儿 可以帮忙解答一下吗
![ss](https://user-images.githubusercontent.com/19222237/29768347-76e71b08-8c18-11e7-878f-a7fb678b5ee0.png)

**Comment by dxxzst** [comment]
下载瓦片图的软件带缓存功能，在你缩放时会自动将加载完的保存至数据库。你也可以按照行政区域下砸。
你也可以试用一下最新版本的下载软件 https://pan.baidu.com/s/1miMF9nM。
