### ISSUE TITLE
下载文件链接失效

### ISSUE THREAD

**Issue by Ken-LiuL** [dxxzst/OfflineMap#3]
网盘里的下载文件失效了， 你这边可以提供一下吗？或者传到git上来

**Comment by dxxzst** [comment]
https://pan.baidu.com/s/1miMF9nM

**Comment by livingbody** [comment]
我怎么显示不出地图呢？

**Comment by Ken-LiuL** [comment]
软件按照readme使用之后 mysql里面并没有图片 不知道是什么原因
