### ISSUE TITLE
你好，下载地图瓦片到本地，瓦片的命名不对

### ISSUE THREAD

**Issue by qooez** [dxxzst/OfflineMap#4]
我将地图瓦片下载到本地之后，可是这个瓦片的名字和我用百度地图api算出来的是不一样，我想问下你这块是怎么解决的呢？

**Comment by wangtao111** [comment]
你好，百度地图下载下来之后经纬度差很多，请问有解决办法吗

**Comment by dxxzst** [comment]
不要下到本地，下载到数据库中

**Comment by qooez** [comment]
@wangtao111  经纬度并没有差很多，我主要应用的不用很精确的，比如某一个城市之类的，只要将这个城市的所有瓦片都下载下来就可以了
