### ISSUE TITLE
请问怎样将瓦片图下载到数据库

### ISSUE THREAD

**Issue by lidongpeng888** [dxxzst/OfflineMap#5]
您好，请问怎么将它下载到mysql数据库，软件目录里面没有相关的config文件 

![image](https://user-images.githubusercontent.com/20453816/41893781-7729af16-794f-11e8-877e-0576be4d4b00.png)

**Comment by dxxzst** [comment]
@lidongpeng888 感觉你下载的不对啊，按照说明里面的链接下载
里面会有MapDownloader.exe.config

**Comment by lidongpeng888** [comment]
恩，好的，谢谢啦
