### ISSUE TITLE
请问下载后的地图能使用百度或者高德的js去进行精确查询吗？

### ISSUE THREAD

**Issue by fufenghua** [dxxzst/OfflineMap#6]
比如把地图下载到数据库之后，我还能使用百度或者高德的api去做聚合，绘点，导航等api 的开发吗？

**Comment by dxxzst** [comment]
@fufenghua 百度的存在一定偏差

**Comment by fufenghua** [comment]
好的，谢谢，我就是想做一个简单的离线地图，基于您的这个功能，再改造高德地图原本的API，然后在本地跑地图功能
