### ISSUE TITLE
关于地图水印问题

### ISSUE THREAD

**Issue by wey580231** [dxxzst/OfflineMap#8]
你好，根据提供的方式，很顺利的搭建起了服务器(灰常感谢)。现在在下载地图时，下载层级更高时发现有有google的水印。请问这个水印是否可以去除？

**Comment by dxxzst** [comment]
@wey580231 水印应该是地图自带的吧，这也没办法

**Comment by wey580231** [comment]
除了二维地图之外，有那种3D场景地图么？或者有相关的资料么？

**Comment by dxxzst** [comment]
@wey580231 https://github.com/iSpring/WebGlobe
你可以看一下这个项目，不过这部里离线版的

**Comment by dxxzst** [comment]
@wey580231 https://github.com/iSpring/WebGlobe
你可以看一下这个项目，不过这部里离线版的

**Comment by dxxzst** [comment]
@wey580231 https://github.com/iSpring/WebGlobe
你可以看一下这个项目，不过这不是离线版的
